# 2025 Taylor Plewe
# This is was inspired by sintab generation scripts I wrote for the 6502, which were inspired by someone else's code, I can't remember who.

import math

NUM_ENTRIES = 64

with open("src/data/sintab.inc", "w") as f:
    f.write("; 2025 Taylor Plewe\n; This file is generated by scripts\\gen_sintab.py")
    f.write(f"; .32 signed fixed-point values of sin(n * ((pi / 2) / {NUM_ENTRIES})) where 0 <= n <= {NUM_ENTRIES}")
    f.write(".data\n\nsintab:\ndd ")
    for i in range(NUM_ENTRIES + 1):
        rad = (i / NUM_ENTRIES) * (math.pi/2)
        f.write(f"{(math.ceil(math.sin(rad) * 0x7fffffff)):08x}h")
        if (i+1) & 0x7 == 0:
            f.write("\ndd ")
        else:
            if i < NUM_ENTRIES:
                f.write(", ")
